version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev


  frontend:

    build:
      context: ./frontend
    image: my-frontend
    container_name: frontend
    ports:
      - "8000:8000"
